FROM golang:1.23-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o client ./cmd/client

FROM alpine:latest

RUN rm -rf /var/cache/apk/* && rm -rf /tmp/*

RUN adduser -D appuser

COPY --from=builder /app/client /client

EXPOSE 8081

USER appuser
ENTRYPOINT ["/client"]
