FROM golang:1.23-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o service ./cmd/service

FROM alpine:latest
WORKDIR /app

RUN rm -rf /var/cache/apk/* && rm -rf /tmp/*

RUN adduser -D appuser

COPY --from=builder /app/service /app/service

COPY --from=builder /app/word_of_wisdom /app/word_of_wisdom

EXPOSE 8080
USER appuser
ENTRYPOINT ["/app/service"]